name: eden_test
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  ably_flutter: ^1.2.22
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  firebase_auth: null
  firebase_core: null
  flutter:
    sdk: flutter
  flutter_localization: ^0.1.14
  flutter_riverpod: ^2.4.6
  flutter_svg: ^2.0.9
  google_sign_in: ^6.1.6
  sign_in_button: ^3.2.0

dev_dependencies:
  custom_lint: ^0.5.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.3.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Red Hat Display
      fonts:
        - asset: assets/fonts/RedHatDisplayRomanBold.ttf
          weight: 700
        - asset: assets/fonts/RedHatDisplayRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RedHatDisplayRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/RedHatDisplayRomanMedium.ttf
          weight: 500
