// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbjoVM3OAfxpEjSYepyompRBa3iQ_nctc',
    appId: '1:764269939915:android:44b70be9a531b0e0385f4e',
    messagingSenderId: '764269939915',
    projectId: 'eden-eab1d',
    databaseURL: 'https://eden-eab1d-default-rtdb.firebaseio.com',
    storageBucket: 'eden-eab1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8bUnFxtSUcj9wTntW14m6tX-Y2J4Rsuc',
    appId: '1:764269939915:ios:ec3e6df288291b21385f4e',
    messagingSenderId: '764269939915',
    projectId: 'eden-eab1d',
    databaseURL: 'https://eden-eab1d-default-rtdb.firebaseio.com',
    storageBucket: 'eden-eab1d.appspot.com',
    iosClientId: '764269939915-8euodqvi89mb026b989sqecuj22kvg4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.edenTest',
  );
}
